### ISSUE TITLE
問題：閱讀欄位一行塞不下

### ISSUE THREAD

**Issue by khenpo-tengye** [karmapa/adarsha2014#3]
![karmapa_github_io_adarsha__3_2](https://cloud.githubusercontent.com/assets/5229877/4622360/2d6385b6-533b-11e4-8957-589fe9602fc3.png)

**Comment by ahsyuyu** [comment]
The bug has been fixed. You can use horizontal scroll to view the whole text. Please see: http://karmapa.github.io/adarsha/ 
Please let me know if it doesn't work.

**Comment by g1ahsia** [comment]
Dear Anne,

I still cannot scroll horizontally. Please check.

thanks,

Allen

**Comment by lamalien** [comment]
已修正
